version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chronos-backend
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - chronos-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chronos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chronos-net

networks:
  chronos-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
        # docker-compose up -d